name: Publish on PyPI

on:
  workflow_run:
    workflows: [ "New release" ]
    types:
      - completed
  workflow_dispatch:

jobs:
  build:
    name: Build wheel and source distribution
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
  
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.7.13"

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Build
        run: uv build

      - name: Upload distribution artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: ./dist

  publish_pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
    if: ${{ needs.build.result == 'success' }}
    environment:
      name: pypi
      url: https://pypi.org/p/pyMOTO/
    
    steps:
      - name: Download distribution artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: ./dist

      - name: Upload to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
      
      - name: Upload to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        if: ${{ github.event_name == 'workflow_run'}}
    