name: PyPI release

on: [push, workflow_dispatch]

jobs:
  tests:
    uses: ./.github/workflows/commit_test.yaml

  build-and-publish:
    name: Build and publish to PyPI
    needs: [tests]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Build
        run: python -m build
      - name: Upload to PyPI
        # if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
          user: __token__
          password: ${{ secrets.TEST_PYPI_TOKEN }}
          repository_url: https://test.pypi.org/
